[versions]
### plguins ###
# ...


### libraries ###
spring = "7.0.0"
log4j = "2.25.2"
junit = "6.0.1"
mockito = "5.20.0"
assertj = "3.27.6"
lombok = "1.18.42"


[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }


[plugins]
# ...
